### ISSUE TITLE
[QA] build fails

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ownbuild#8]
Seen while trying the build commands shown in the README on Win11

Setup: Follow the instructions for visual studio 2022 / 2019 in the README.
Then run the command shown in the README.

```
python3 ownbuild.py owncloud-client
```
runs for long time, compiles many files, but eventually runs into an error:

```
...
*** Action: post-qmerge for binary/mysql ***
*** Craft all succeeded: binary/mysql after 4 minutes 40 seconds ***
========================================================================================================================
*** Handling package: libs/icu, action: all ***
*** Action: fetch-binary for libs/icu ***
Could not find libs/icu=67.1 in https://files.kde.org/craft/master/22.07/windows/msvc2019_64/cl/RelWithDebInfo
Could not find libs/icu=67.1 in https://files.kde.org/craft/master/22.07/windows/msvc2019_64/cl/Release
*** libs/icu not found in cache ***
*** Action: fetch for libs/icu ***
wget https://github.com/unicode-org/icu/releases/download/release-67-1/icu4c-67_1-src.tgz
C:/CraftRoot/download/archive 100%[=================================================>]  23.38M  1.51MB/s    in 16s
*** Action: unpack for libs/icu ***
executing command: C:\CraftRoot\dev-utils\bin\7za.exe x C:\CraftRoot\download\archives\libs\icu\icu4c-67_1-src.tgz -so -bsp2 | C:\CraftRoot\etc\virtualenv\3\Scripts\python.exe -u C:\Users\User\ownbuild\2.10\windows-msvc2019_64-cl\craft\bin\untar.py C:\CraftRoot\build\_\9245fc20
*** Action: compile for libs/icu ***
*** Craft all succeeded: libs/icu after 22 seconds ***
list index out of range
Traceback (most recent call last):
  File "C:\Users\User\ownbuild\2.10\windows-msvc2019_64-cl\craft\bin\craft.py", line 274, in <module>
    success = main(timer)
  File "C:\Users\User\ownbuild\2.10\windows-msvc2019_64-cl\craft\bin\craft.py", line 264, in main
    if not CraftCommands.run(package, action, tempArgs):
  File "C:\Users\User\ownbuild\2.10\windows-msvc2019_64-cl\craft\bin\CraftCommands.py", line 425, in run
    if not handlePackage(info, action, directTargets=directTargets):
  File "C:\Users\User\ownbuild\2.10\windows-msvc2019_64-cl\craft\bin\CraftCommands.py", line 94, in handlePackage
    success = doExec(package, action)
  File "C:\Users\User\ownbuild\2.10\windows-msvc2019_64-cl\craft\bin\CraftCommands.py", line 58, in doExec
    ret = package.instance.runAction(action)
  File "C:\Users\User\ownbuild\2.10\windows-msvc2019_64-cl\craft\bin\Package\PackageBase.py", line 247, in runAction
    if not getattr(self, step)():
  File "C:\Users\User\ownbuild\2.10\windows-msvc2019_64-cl\craft\bin\BuildSystem\BuildSystemBase.py", line 89, in compile
    return configure() and make()
  File "C:\Users\User\ownbuild\2.10\windows-msvc2019_64-cl\craft\bin\BuildSystem\AutoToolsBuildSystem.py", line 60, in configure
    self.shell.environment["CFLAGS"] = self.subinfo.options.configure.cflags + " " + self.shell.environment["CFLAGS"]
  File "C:\Users\User\ownbuild\2.10\windows-msvc2019_64-cl\craft\bin\shells.py", line 112, in environment
    latestAutomake = automake[-1][1]
IndexError: list index out of range
Craft stopped with out completing ['libs/icu', 'libs/libzstd', 'libs/libpng', 'libs/libjpeg-turbo', 'libs/sqlite', 'libs/libbzip2', 'libs/pcre2', 'libs/freetype', 'libs/harfbuzz', 'dev-utils/qtbinpatcher', 'dev-utils/flexbison', 'libs/qt5/qtbase', 'libs/qt5/qtsvg', 'libs/d3dcompiler', 'libs/qt5/qtdeclarative', 'libs/qt5/qttools', 'libs/qt5/qttranslations', 'kde/frameworks/extra-cmake-modules', 'libs/qt5/qtxmlpatterns', 'qt-libs/qtkeychain']
Command C:\CraftRoot\etc\virtualenv\3\Scripts\python.exe -u C:\Users\User\ownbuild\2.10\windows-msvc2019_64-cl\craft\bin\craft.py --unshelve C:\Users\User\ownbuild\2.10\.craft.shelf failed with exit code: 1
Failed to setup craft
```

Same error for the more specific command
```
python3 ownbuild.py --branch 2.10 --target windows-msvc2019_64--cl

```

**Comment by jnweiger** [comment]
![image](https://user-images.githubusercontent.com/1108546/177391814-4f8ac84f-8ccd-4bc2-b609-f626f07fb55b.png)

@dschmidt @TheOneRing Upgrade something to icu=71.1 ??

**Comment by TheOneRing** [comment]
Please use the master branch.
The issue was fixed in craft a long time ago but we use version pinning for 2.10 so we check out a super old version of craft.
During the switching of branches it might occur that it tries to install for example icu 71.1 which is not available in the old version.
You can work around that issue by manually checking out the revisions but I'd recommend that you just use the master config.

**Comment by TheOneRing** [comment]
I just saw that you run ownbuild.py from an existing CraftRoot.
They don't mix pleas use a fresh environment.

**Comment by TheOneRing** [comment]
Please specify your environment.

**Comment by jnweiger** [comment]
Good to know that ownbuild should not work after setting up a craftroot.

```
craft owncloud-client
```
also fails:

![image](https://user-images.githubusercontent.com/1108546/177510894-0f143287-fe4d-4fa8-bb66-9482441f2ffd.png)
